set(arguments)
if(COMPREHENSIVE)
    list(APPEND arguments --stats comprehensive --threads 1)
endif()
if(FORMAT)
    list(APPEND arguments --format ${FORMAT})
endif()
execute_process(COMMAND "${RUST}" ${arguments} "${FASTA}" "${GFA}"
    RESULT_VARIABLE rust_status OUTPUT_VARIABLE rust_out ERROR_VARIABLE rust_err)
execute_process(COMMAND "${CPP}" ${arguments} "${FASTA}" "${GFA}"
    RESULT_VARIABLE cpp_status OUTPUT_VARIABLE cpp_out ERROR_VARIABLE cpp_err)
if(NOT rust_status EQUAL cpp_status)
    message(FATAL_ERROR "exit mismatch: Rust=${rust_status}, C++=${cpp_status}")
endif()
if(NOT rust_out STREQUAL cpp_out)
    message(FATAL_ERROR "stdout mismatch\nRust:\n${rust_out}\nC++:\n${cpp_out}")
endif()
if(NOT rust_err STREQUAL cpp_err)
    message(FATAL_ERROR "stderr mismatch\nRust:\n${rust_err}\nC++:\n${cpp_err}")
endif()
